import { Component } from '@angular/core';

// const log = (target:any, name:any, descriptor:any) => {
//     console.log(target, name, descriptor)

//     const original = descriptor.value

//     descriptor.value = function(...args:any){
//       console.log("Arguments ", args, " were passed in this function")
//       const result = original.apply(this, args)
//       console.log("The result of the fucntion is ", result)
//       return result
//     }
//     return descriptor
// }


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'intro2angular';

  constructor(){
    // console.log("The statement was generated by the constructor", this.aSimpleMethod(12))
  }

  // @log
  // aSimpleMethod(a:any){
  //   return a*a
  // }
}
 